### PR TITLE
Bump to 3.3.7

### PR DESCRIPTION
**Pull request by jekkos**
Bump can be done if we have no other critical things to fix for the current release.

### CODE REVIEW

**Comment by jekkos** [comment]
Holding this back until we know we did not break too much stuff.

**Comment by daN4cat** [comment]
Unless you plan to bump 3.3.6, a new release fixing just two odd bugs will be required.
This time I would not wait too long because the deleted issue is annoying.

**Comment by jekkos** [comment]
Ok the bug is fixed and in master now , will merge this one and then wait a bit until hopefully no more bugs are found :)

**Comment by minhazulOO7** [comment]
> Unless you plan to bump 3.3.6, a new release fixing just two odd bugs will be required. This time I would not wait too long because the deleted issue is annoying.

Bro! Any delete issue with 3.3.6? Just want to get sure because will be updating soon! Please reply when you are free! 😱

**Comment by jekkos** [comment]
In master now

**Pull request closed without merging**
