### PR TITLE
Fix stock location crud (#2965)

### PR DESCRIPTION
**Pull request by jekkos**
This should fix the stock location crud issue. Tested locally on docker compose and seems fine afaik.

### CODE REVIEW

**Review by daN4cat — APPROVED** [review]

**Comment by andriux1990** [comment]
I just ran tests and the problem persists

**Comment by andriux1990** [comment]
This is how I find out
jekkos2
I had 7 extra locations other than the main one .. then I deleted them all and only left the first
when I want to show the stock suggestions in the searches I see the locations that should be eliminated
jekkos

**Comment by andriux1990** [comment]
Testing the latest version of bintray
os1

os2
I have a locatiion called stock, then I create 3 more location to show that the new locations hold the quantities of the old locations. These new locations have names that are different from the old ones.
os3

**Comment by jekkos** [comment]
thanks for testing @andriux1990 . I'll review the changeset somewhere this week.

**Comment by jekkos** [comment]
@andriux1990 I have tested again myself and can't reproduce this behavior directly. I have one stock location, add  some quantities, then add another one. The quantities for this new one is always 0.

**Comment by jekkos** [comment]
Good that you show the version hash, it does seem to be one after the merge of my fix.

**Comment by jekkos** [comment]
Screenshot from 2020-10-27 23-02-19

**Pull request merged**
