### PR TITLE
EG to LB

### PR DESCRIPTION
**Pull request by WebShells**
Although it fits for all arabic language countries, yet it's the most accurate locale to be used since
most of AR Translation were made for LB language.

### CODE REVIEW

**Comment by daN4cat** [comment]
Why not duplicate? If I remember right there was a guy who created the ar-EG and would be better retain it.

**Comment by WebShells** [comment]
@daN4cat i handled the translation part for the past period, it was around 28% translated as for ar-EG. Am not sure if it's better to keep both; in this case, we should have some one from EG willing to skim double check the strings... Whatever you find more suitable.

**Comment by jekkos** [comment]
He might be notified through weblate once strings are updated, some let's hope he comes back and improves the translation :)

**Comment by WebShells** [comment]
Added back ar-EG to the list 👍 we can merge...

**Pull request merged**
