### PR TITLE
onclick selection item

### PR DESCRIPTION
**Pull request by andriux1990**
It frustrates me a lot to have to be double clicking to be able to select all the content when changing the price or quantity.

a simple but useful change

### CODE REVIEW

**Comment by WebShells** [comment]
@andriux1990 can you please add the line on all forms, clients, suppliers, etc...
So we can merge all at once ? 
Thanks, all prefers a single click rather than 2, somehow it's frustrating.

**Comment by andriux1990** [comment]
ok I'll do it now

**Comment by andriux1990** [comment]
I think onclick is only necessary in these places

**Comment by jekkos** [comment]
Indeed this code is already in place in the sales register. I'll merge this one.

**Comment by daN4cat** [comment]
Thanks @andriux1990 for the contribution!

**Pull request merged**
