### PR TITLE
Update invoice_email.css

### PR DESCRIPTION
**Pull request by tuthanika**
Error show utf-8 font

### CODE REVIEW

**Comment by daN4cat** [comment]
Thank you for your contribution. What is the problem you are fixing with this change?

**Comment by tuthanika** [comment]
> Thank you for your contribution. What is the problem you are fixing with this change?

When sending the invoice by email, the generated pdf file has the font error utf-8

**Comment by SteveIreland** [comment]
Is anyone else experiencing this issue?  If this is an error then it seems like we would need a more complete solution (something that works for all PDF renderings).

**Comment by jekkos** [comment]
@SteveIreland indeed we should define the fonts in order of preference, if one is not available it should fallback to another.

**Comment by daN4cat** [comment]
@SteveIreland is this something to merge with the other invoice email change?

**Comment by WebShells** [comment]
I think so

**Comment by SteveIreland** [comment]
The changes in this pull request have been included in the #2660 pul request

**Pull request closed without merging**
