### PR TITLE
Grey out/disable Submit button after validation to prevent double sub

### PR DESCRIPTION
**Pull request by objecttothis**
These are small changes that mainly affect long-running scripts such as CSV imports.  The idea is that if the script is long running, there is no real feedback that your "click" of submit registered, so you might click it again.  This disables the submit and changes the opacity to prevent double submissions.

### CODE REVIEW

**Comment by daN4cat** [comment]
This issue of double submission was fixed by @jekkos centrally. Maybe we should add the greying of the button in the same place for all the forms?

**Comment by objecttothis** [comment]
> 
> 
> This issue of double submission was fixed by @jekkos centrally. Maybe we should add the greying of the button in the same place for all the forms?

Yeah, if there is a way to disable and grey out the submit button in one central place for all submit buttons then I'm all ears.  perhaps even better would be to replace the submit text with a spinning gif... the idea is to show that the system is working on it.  Good to know that double submission is no longer possible.

**Comment by odiea** [comment]
I don't know if this would be where you could make those changes? This is where the submit and delete buttons are shown 
https://github.com/opensourcepos/opensourcepos/blob/2dec15c7605d599acb98ada90459121c55e3cda1/public/js/manage_tables.js

**Comment by jekkos** [comment]
@objecttothis as @odiea suggests, I think if you set submitted flag on the validator to true, that it should disable submit

**Comment by jekkos** [comment]
https://github.com/opensourcepos/opensourcepos/blob/2dec15c7605d599acb98ada90459121c55e3cda1/public/js/manage_tables.js#L20

**Comment by objecttothis** [comment]
> 
> 
> https://github.com/opensourcepos/opensourcepos/blob/2dec15c7605d599acb98ada90459121c55e3cda1/public/js/manage_tables.js#L20

OK, that's a better solution.  Any problem with me also reducing the opacity to 50% so that it provides a visual cue that the button click has registered?  Part of the thing that we need to make sure works is that the validation doesn't break.  If there is a validation error, they still need to be able to click submit, otherwise they get stuck in a situation where they can't click submit because the submit button doesn't get re-enabled on validation errors.

**Comment by daN4cat** [comment]
Please test the click of submit -> greying -> click outside the form or press ESC and see what happens. Also try to reopen the form after that scenario to make sure the submit button is fine / works fine.

**Comment by objecttothis** [comment]
@daN4cat I'd prefer that this didn't hold up 3.3.4.  I'll be working on it tomorrow, but I picked it up while biding my time for 3.3.4 to be released.  It was on my list anyway.  Can we push it to 3.4.0?

**Comment by jekkos** [comment]
@objecttothis sure I moved the target milestone. I guess it's something you need together with the import fixes anyway

**Comment by jekkos** [comment]
Also fine for me to add this opacity fix in the manage_table. Good to have a visual indication that the submit is disabled.

**Comment by daN4cat** [comment]
I would prefer for 3.3.4 because it's a small thing really.

**Comment by objecttothis** [comment]
Fine, but my understanding of bug fix releases is that it isn't good practice to introduce new features.  I will work on it tomorrow.

**Comment by objecttothis** [comment]
@jekkos I'm having a difficult time implementing this feature at that location.  I'm fairly new to jQuery and javascript, so it's likely I'm doing something wrong.

As soon as I insert `$("#submit").prop('disabled',true).css('opacity',0.5);` into that if statement and remove it from the form view, it doesn't work.  I don't know if this is a scope issue or what.  ideas?

**Comment by odiea** [comment]
@objecttothis did you run grunt on the program after you made the changes.

**Comment by objecttothis** [comment]
> 
> 
> @objecttothis did you run grunt on the program after you made the changes.

I did not.  I wasn't aware that I needed to do this.  Is that file minified somewhere?  Like I said, I'm fairly new to JavaScript and jQuery, so don't really know what I'm doing.  I just know that the line of code produces the desired result when it's placed in the location in the commit.  How would I go about running grunt against it?

**Comment by odiea** [comment]
I guess it is. When I was trying to change that file nothing would work until I ran grunt on it. As per @jekkos

**Comment by odiea** [comment]
Do you have composer install ?

**Comment by odiea** [comment]
I am a windows user so I don't know how the Linux version would work

**Comment by objecttothis** [comment]
> 
> 
> I am a windows user so I don't know how the Linux version would work

I'm a windows user as well but our server is freebsd so I'm doing this all through the command line.  I'm reading through the documentation at https://github.com/opensourcepos/opensourcepos/wiki/OSPOS-Environment-Development and slowly making progress.  One thing I want to confirm is that since our production installation is on the same server, I only want to be running anything against the development installation.  Do I just run these from the root of the project that I am doing development in then? 

I figured eventually I would need to learn how to build the project.

**Comment by odiea** [comment]
From command I cd to the dir where the program is installed then run grunt on it

**Comment by objecttothis** [comment]
When I try to run

dev@chiraq:/usr/local/www/public_html/pos_import % grunt cssmin

I get the error:

A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile.

/pos_import/ is the root directory.  Is that not where I should be running the CLI command?

**Comment by odiea** [comment]
Have you installed and run Composer on the dir yet. I believe I had to do that initially to get grunt to work.

**Comment by objecttothis** [comment]
ugh.  getting this setup has been a real pain.  Dependencies on top of dependencies.

I got docker-compose installed but when I run `docker-compose -f docker-compose.dev.yml build`

I get the error
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

I haven't configured docker before, so it's unclear about what configuration I'm missing here.  This is on a FreeBSD server

**Comment by objecttothis** [comment]
I think I figured it out...

https://wiki.freebsd.org/Docker#zroot

Apparently Docker is broken in FreeBSD, so It appears I won't be able to use Docker as a route to grunt.

**Comment by objecttothis** [comment]
I have node 15.7.0 installed, npm 6.14.0 installed.  I ran `npm install -g grunt` and get

npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt/bin/grunt
+ grunt@1.3.0
updated 1 package in 9.785s

Then install bower with `npm install -g bower` and get 

/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
+ bower@1.8.12
updated 1 package in 1.773s

I have php74-composer2-2.0.8 installed... should I be using composer 1?

In the docs @jekkos says that I need to run bin/devinstall.sh but I can't find that script anywhere in the project files.

When I run `npm install --only=dev` I get

npm WARN saveError ENOENT: no such file or directory, open '/usr/local/www/public_html/pos_import/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/www/public_html/pos_import/package.json'
npm WARN pos_import No description
npm WARN pos_import No repository field.
npm WARN pos_import No README data
npm WARN pos_import No license field.

audited 312 packages in 1.55s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

so there is clearly something not in place.

Trying to run `bower install` just gives me the error `bower ENOENT        No bower.json present`

**Comment by odiea** [comment]
If you can download the current code from the front page and build that you will have a good place to start. Not any new build in install md. I usually download the code. Run composer install,    npm install --only=dev  then    grunt -f. This should give you some starting point. And yes you will see a lot of deprecated things.

**Comment by objecttothis** [comment]
> 
> 
> If you can download the current code from the front page and build that you will have a good place to start. Not any new build in install md. I usually download the code. Run composer install, npm install --only=dev then grunt -f. This should give you some starting point. And yes you will see a lot of deprecated things.

OK, this might be the issue.  I'm working off a build in bintray.

**Comment by odiea** [comment]
Then once it appears to be working I will then take and replace  the application folder with a good working application folder that has your programming changes

**Comment by odiea** [comment]
After you get it up and running change the manage_tables js the run grunt again to have the changes start working

**Comment by objecttothis** [comment]
I'm off tomorrow and Monday, so I'll get to this Tuesday unless someone else wants to do it or punt it to 3.4.0 so that we can release 3.3.4

**Comment by jekkos** [comment]
@objecttothis you don't need to run the minification necessarily, you can just append `?debug=true` to your url and the javascript file will be loaded directly. It's the easiest and fastest way to test such changes.

travis minifies the files automatically so no need to do it yourself if you know that the debug version is working..

**Comment by objecttothis** [comment]
@jekkos I was able to get it to work by adding `?debug=true` to the URL.  Here is where I'm stuck:

If I modify the submit function in manage_tables.js to

```
	var submit = function(button_id) {
		return function(dlog_ref) {
			btn_id = button_id;
			dialog_ref = dlog_ref;
			if (button_id == 'submit') {
				$('#submit').prop('disabled',true).css('opacity', 0.5);
				$('form', dlog_ref.$modalBody).first().submit();
			}
			return false;
		}
	};
```

It greys out and disables the submit button on click as it should.  The only problem is that if there is a missing or invalid required field, the submit doesn't get re-enabled.  When I was doing this per file, I was greying out the submit after the checks completed.  In this file, I tried to insert `$('#submit').prop('disabled', false).css('opacity', 1);` at various points in the code, but it never runs that line of code or it does, but doesn't have the proper scope (I can't tell).  What I do know is that `$('#submit').prop('disabled', false).css('opacity', 1);` does work, because if I place it right after the disable, it re-enables it properly.

The place I think it should go it in the submit_handler, but like I said, it doesn't seem to work:

```
	var submit_handler = function(url) {
		return function (resource, response) {
			var id = response.id;
			if (!response.success) {
				$('#submit').prop('disabled', false).css('opacity', 1);
				$.notify(response.message, { type: 'danger' });
			}
```

Anyone have any ideas?

**Comment by jekkos** [comment]
> @jekkos I was able to get it to work by adding `?debug=true` to the URL. Here is where I'm stuck:
> 
> If I modify the submit function in manage_tables.js to
> 
> ```
> 	var submit = function(button_id) {
> 		return function(dlog_ref) {
> 			btn_id = button_id;
> 			dialog_ref = dlog_ref;
> 			if (button_id == 'submit') {
> 				$('#submit').prop('disabled',true).css('opacity', 0.5);
> 				$('form', dlog_ref.$modalBody).first().submit();
> 			}
> 			return false;
> 		}
> 	};
> ```
> 
> It greys out and disables the submit button on click as it should. The only problem is that if there is a missing or invalid required field, the submit doesn't get re-enabled for the user to correct the mistake and click submit again. When I was doing this per file, I was greying out the submit after the checks completed. In this file, I tried to insert `$('#submit').prop('disabled', false).css('opacity', 1);` at various points in the code, but it never runs that line of code or it does, but doesn't have the proper scope (I can't tell). What I do know is that `$('#submit').prop('disabled', false).css('opacity', 1);` does work, because if I place it right after the disable, it re-enables it properly.
> 
> The place I think it should go it in the submit_handler, but like I said, it doesn't seem to work:
> 
> ```
> 	var submit_handler = function(url) {
> 		return function (resource, response) {
> 			var id = response.id;
> 			if (!response.success) {
> 				$('#submit').prop('disabled', false).css('opacity', 1);
> 				$.notify(response.message, { type: 'danger' });
> 			}
> ```
> 
> Anyone have any ideas?

@objecttothis the code you refer to seems outdated?

**Comment by objecttothis** [comment]
> @objecttothis the code you refer to seems outdated?
> I think you should only disable if the validation went fine and when the form is actually submitted. This flag is present in the line below
> 
> https://github.com/opensourcepos/opensourcepos/blob/6e546a098ed986aaa8d4ef46fc8d0297ead63e9b/public/js/manage_tables.js#L17

Oops, you were right.  I corrected that and am using the latest master build.

This isn't working the way that you suggested.

If I place
```
			if(submitted){
				$('#submit').prop('disabled', true).css('opacity', 0.5);
			}
```
It does not grey out the submit button.  outside of that if statement it works fine with the problem of it disabling the submit button when there is a validation error.

I also tried placing it inside

```
			if (button_id == 'submit' && (!submitted && btn_id != "btnNew")) {
				form.submit();
			}
```

But then it didn't grey out the submit button at all.  I also tried putting it in an if statement testing validator, but it would not disable the button.  The console in the browser isn't giving me any errors so I'm not sure how to debug whether the validator variable is producing what I think it should.

**Comment by jekkos** [comment]
@objecttothis can you try this snippet? 

```
			if (submitted && validator.valid)
			{
				$('#submit').prop('disabled', true).css('opacity', 0.5);
			}
```

**Comment by jekkos** [comment]
I tested it locally but currently have no scenario in which this grey out would apply (I suppose it's useful only when you have a blocking dialog due to a server side request that is being processed). The snippet normally only disables if
* you click submit
* the form is valid
* the form is submitted

**Comment by objecttothis** [comment]
> 
> 
> I tested it locally but currently have no scenario in which this grey out would apply (I suppose it's useful only when you have a blocking dialog due to a server side request that is being processed). The snippet normally only disables if
> 
>     * you click submit
> 
>     * the form is valid
> 
>     * the form is submitted

When working properly, it should grey out any time the submit button is clicked, even if only for a moment.  Your code snippet isn't working and I think I have some clues.  I wrapped (`button_id == "submit"`, `validator` and `submitted`) in individual `console.log()` statements and here is what I got when submitting a form with no validation errors.

image

`button_id == "submit"` evaluates to true as it should.

the dump of validator doesn't show me an element called "valid".  There is an element called 'invalid' which contains an empty object when there are no validation errors and which contains a populated object with the validation error and messages when there is a validation error.

`submitted` produces undefined.  I'm a little puzzled as to why that is because `const submitted = validator && validator.formSubmitted;` is above that... unless the boolean of an object produces undesirable results.

**Comment by objecttothis** [comment]
also, note that validator.formSubmitted always evaluates to false... even when there are no validation errors.

**Comment by objecttothis** [comment]
OK, here is how I was able to fix this.  I just tested for whether validator.invalid was an empty object or not.  Do you see any holes in this method?

```
			const is_valid = !$.isEmptyObject(validator.invalid)

			btn_id = button_id;
			dialog_ref = dlog_ref;

			if (button_id == 'submit' && is_valid){
				$('#submit').prop('disabled', true).css('opacity', 0.5);
			}
```

**Comment by objecttothis** [comment]
> 
> 
> Please test the click of submit -> greying -> click outside the form or press ESC and see what happens. Also try to reopen the form after that scenario to make sure the submit button is fine / works fine.

@daN4cat I tested these scenarios and the behavior is correct.  Clicking outside the window or pressing escape causes the window to disappear (same as before).  Re-opening the form after that scenario reopens the form as it should.

**Comment by objecttothis** [comment]
@jekkos the only scenario in which it does not grey out the submit like it should is after clicking the "new" button.  If I fill in the values then click "new", it creates the item (you can see the toast notification), then keeps the window open.  However when I click submit this time (with or without validation errors) it does the opposite behavior that it should.

no validation errors > New > validation errors > Submit
Greys out the submit which is not what you would want.

no validation errors > New > No validation errors > Submit
doesn't grey out submit, but you would want that in this case.

Perhaps I need to include a check for the new button somehow?  Or maybe it isn't refreshing the window when new gets clicked?

**Comment by jekkos** [comment]
> @jekkos the only scenario in which it does not grey out the submit like it should is after clicking the "new" button. If I fill in the values then click "new", it creates the item (you can see the toast notification), then keeps the window open. However when I click submit this time (with or without validation errors) it does the opposite behavior that it should.
> 
> no validation errors > New > validation errors > Submit
> Greys out the submit which is not what you would want.
> 
> no validation errors > New > No validation errors > Submit
> doesn't grey out submit, but you would want that in this case.
> 
> Perhaps I need to include a check for the new button somehow? Or maybe it isn't refreshing the window when new gets clicked?

The condition to disable is
* everything is valid (not the case after clicking new)
* you click submit (this is the case).

So not sure why it would grey out in this case.. it means that the validator is empty while you see validation errors?  Maybe just set a breakpoint to inspect the variables at that point in the code as I can only guess from here.

**Comment by objecttothis** [comment]
OK, I pushed a commit that fixes this issue.  If someone could do a code review and let me know.  Also, I've tested multiple scenarios but if someone could test this as well and tell me if they are able to find any issues, that would be helpful.

**Review by jekkos — APPROVED** [review]

**Comment by jekkos** [comment]
I wanted to test quickly before merge but I think this last travis change is not in this branch yet (so I'm running into this docker rate limtitation again). Merged to master and let's check again after deploy. If it's fine then we'll release the next minor version.

**Comment by jekkos** [comment]
Did a quick test and it seems that there is still an issue when you click submit twice on an invalid form..

**Comment by objecttothis** [comment]
> 
> 
> @objecttothis Did a quick test and it seems that there is still an issue when you click submit twice on an invalid form..

I was just able to duplicate this issue.  I will work on it.

**Pull request merged**
