### PR TITLE
Enable table data escape (#3379)

### PR DESCRIPTION
**Pull request by jekkos**
Try to mitigate XSS for all modules by enabling bootstrap tables escape.

### CODE REVIEW

**Comment by daN4cat** [comment]
If we do this we need to disable in config the XSS filter.

**Comment by jekkos** [comment]
> If we do this we need to disable in config the XSS filter.

Maybe we can try to combine.. as it seems that this specific payload is able to bypass the CI escape?

**Comment by jekkos** [comment]
@daN4cat what this flag does is[ documented here](https://bootstrap-table.com/docs/api/table-options/). So it's not a real xss escape but rather a html entity rendering step.

**Comment by jekkos** [comment]
Thanks for testing @odia. I think this should be enabled per column instead.

**Pull request merged**
