### PR TITLE
Publish to github releases (#3110)

### PR DESCRIPTION
**Pull request by jekkos**
Let's try and see if we can push a build to github releases from travis

### CODE REVIEW

**Comment by objecttothis** [comment]
@jekkos I removed the reference to bintray in the readme.  Do we have anything that we can use in the meantime?

**Comment by jekkos** [comment]
The issue here is that travis is unable to parse the config file maybe due to a wrong format. Currently I think the only way is to build locally

**Comment by jekkos** [comment]
It took me some fiddling to get it to work but I think it works the way I want now.

We will always have a tagged commit in each branch that points to the last build that was produced for that branch. Those build will be available in the releases section as a 'pre-release'.

**Comment by jekkos** [comment]
the final zip files have the same naming as the ones that were pushed to bintray, so this might be recognizable.

**Pull request merged**
