### PR TITLE
Expand flexibility of parse_decimal function

### PR DESCRIPTION
**Pull request by SteveIreland**
Add support to parse_decimal function for tax_decimals and quantity_decimals parsing.

This addresses the problem reported in issue #2626

### CODE REVIEW

**Comment by jekkos** [comment]
Thanks for the fix @SteveIreland! Just one minor remark on code style.

**Comment by SteveIreland** [comment]
@jekkos Not sure why, but I'm not seeing your "minor remark on code style".

**Comment by jekkos** [comment]
Ok forgot to submit the review. I think it might be quick to change using intellij's refactor functionality.

**Comment by jekkos** [comment]
I went ahead and applied the suggestions myself

**Pull request merged**
