### PR TITLE
add fields to table.sql discount on sales fixed

### PR DESCRIPTION
**Pull request by erastus**

### CODE REVIEW

**Comment by erastus** [comment]
@SteveIreland  you mean tables.sql

**Comment by erastus** [comment]
@SteveIreland  I have made a new installation and does not generate errors, I have a complete database and it does not generate any errors

**Comment by SteveIreland** [comment]
Yes you are correct. Sorry, I was responding via my iPhone at a Mexican restaurant with a margarita in front of me. Thanks for the fix!

**Comment by erastus** [comment]
@SteveIreland  Thanks, I'm Mexican.

**Comment by daN4cat** [comment]
Sorry, but I don't see how this could fix the problem. It changes nothing and the problem it's still there.

I'm using the docker container on the local laptop and it creates everything from scratch.

**Comment by erastus** [comment]
The problem occurs because you do not create the database.sql file with the new fields in the tables.sql file

**Comment by erastus** [comment]
@daN4cat  try to generate the database.sql file with these changes

**Comment by daN4cat** [comment]
The migration script runs the first time and updates the database. It's not that issue either.

**Comment by erastus** [comment]
you can check if in your table ospos_app_config you have the field default_sales_discount_type

**Comment by daN4cat** [comment]
it's probably related to the docker container and database upgrade during migration.
The migration seems executed but something is not right.

**Comment by daN4cat** [comment]
Right, during yesterday's discussion I copied and pasted the following:

INSERT INTO ospos_app_config (key, value) VALUES
('default_sales_discount_type', '0');

and that in latest mariadb is not allowed, where this is correct:

INSERT INTO `ospos_app_config` (`key`, `value`) VALUES
('default_sales_discount_type', '0');

spot the missing `

**Comment by erastus** [comment]
@daN4cat what is the solution, is this pull-requests necessary?

**Comment by daN4cat** [comment]
It's fixed.

**Pull request closed without merging**
