### PR TITLE
improve autoselect amounts featured

### PR DESCRIPTION
**Pull request by mckaygerhard**
* improve autoselect amounts as per discuted in #1863 in amount_tendered and item count
* TODO: this can be a option configuration in office, but for now made directly in the code

### CODE REVIEW

**Comment by jekkos** [comment]
so this change is not usable then after all?

**Comment by odiea** [comment]
It works for me.

**Comment by mckaygerhard** [comment]
hi @jekkos  and @odiea this was already done by @daN4cat recently.. and seems his commit was better

**Comment by WebShells** [comment]
Well, it is actually in some cases better than back spacing couple of times...

**Comment by daN4cat** [comment]
It's in master already

**Pull request closed without merging**
