### PR TITLE
Database Fix

### PR DESCRIPTION
**Pull request by SteveIreland**
This adds a couple of missing constraints.  I haven't been able to test with the most recent master yet because of the bintray issues so please don't merge it yet.

### CODE REVIEW

**Comment by SteveIreland** [comment]
Don't merge just yet.  I'm planning on adding a couple of constraints to the tax rate table.   I just wanted to someone to take a look at these changes to make sure that I'm meeting expectations.

**Comment by SteveIreland** [comment]
The last changes that I identified have been added to this pull request.  If there are any other missing database constraints just let me know and I'll be happy to add them.

**Comment by daN4cat** [comment]
I've added a comment even if not related specifically to this change, but given we are adding indexes I wonder if we should check we have everything in place. For instance trans_time is used for Items data range selection and there is no index and probably non foreign key neither.

**Comment by SteveIreland** [comment]
I've applied an index to three of the timestamps I've found.  That should certainly improve the performance of any filters or queries that involve the timestamp.

**Comment by daN4cat** [comment]
Thanks for the work @SteveIreland. I've added a date index to expenses table, tested and merged.

**Comment by jekkos** [comment]
Not sure if adding indexes for singe fields will always help us out here. We probably need to check which queries are ran and then explain them to see which (combined) indexes we need to create.

**Pull request merged**
