### PR TITLE
Use backend for amount validation (#2020, #2018)

### PR DESCRIPTION
**Pull request by jekkos**
*    Reason why csrf sometimes didnt work, was probably because the dateFilter callback was not always done (setup of the token is now done in the hook itself, before returning the result)
*    Giftcard amount formatting was broken, now works and cleans user input interactively
*    Same for expenses form

Would be nice if someone has some time to do a thorough validation on demo.

### CODE REVIEW

**Comment by jekkos** [comment]
Maybe i should leave invalid values untouched instead of resetting them? Any ideas here?

**Comment by WebShells** [comment]
@jekkos for gift cards and expenses things are running smoothly over the demo...

**Comment by jekkos** [comment]
@Webshells can you also test locale config, MailChimp, barcode validation to see if it works well with csrf?

**Comment by jekkos** [comment]
@daN4cat I checked the double submit issue, it does not occur after adding again a form_setup call. I'll verify again on demo  right away.

**Comment by daN4cat** [comment]
Tested and I still see the issue (BTW I'm using PHP7.1)

**Comment by jekkos** [comment]
For my understanding, what you do is just click a submit button twice in config?

**Comment by daN4cat** [comment]
I click submit once then after the pop up window I click it again and from Inspector I see the error.

**Comment by jekkos** [comment]
Ok I can reproduce it..

**Comment by daN4cat** [comment]
Tricky one to catch...

**Comment by jekkos** [comment]
I'll try to look into it this week, went off for the weekend again..

**Comment by jekkos** [comment]
OK think I have it fixed now. Issue was that I was trying to reinstall the new token in a form that wasn't yet in the DOM (so from the $.ajax call that parsed the DOM response). Instead of this the token refresh is done from the ajaxComplete() method now (seems to be a new function in current jQuery).

Testing/validation on demo would be nice @WebShells

**Comment by daN4cat** [comment]
Sounds good

**Comment by odiea** [comment]
Demo Server Bad Gateway

**Comment by mckaygerhard** [comment]
interesting demo server it's not apache... but ospos must run recomended in apache!

**Comment by daN4cat** [comment]
@mckaygerhard never heard of running a reverse proxy in front of a web server? That's standard practise and usually done using nginx.
BTW OSPOS can also run on nginx and there is a tutorial how to set it up. So no, it's not only Apache.

**Comment by jekkos** [comment]
Ok demo should be running this branch now

**Comment by jekkos** [comment]
@mckaygerhard in this case ospos is still running on apache (in the docker config), but it's just easier to setup ssl using let'sencrypt and nginx so..

**Comment by daN4cat** [comment]
@mckaygerhard I would suggest to tune your expectations to the right level as we are not committing ourselves to support 50 OSPOS stations nor enterprise deployments.
There are professional people to deal with those type of problems and they make sure they are paid for that type of job.

**Comment by mckaygerhard** [comment]
i cannot track correctly either backport this pull due there's too code style changes (innecesary in a pull request) can be **code changes next time made outside/after the pull request! there's too many changes not related with the bugfix!**

**Comment by jekkos** [comment]
So no more known issues here? Ready to merge?

**Comment by SteveIreland** [comment]
I'm ready!

**Comment by mckaygerhard** [comment]
and for 3.2.3 version ? there's no backport? i cannot track due those non-related changes

**Comment by daN4cat** [comment]
@jekkos I didn't have the time to test. I'm maxed out. It's a tricky change and needs to be tested properly.

**Comment by jekkos** [comment]
I tested some regular flow.. as well as most of the config submits, seemed to be all fine. In case something else pops up then I'll take care of it, so I'll pull the trigger here now.

**Comment by SteveIreland** [comment]
Excellent, I'll rebase all of my stuff over it tonight.

**Pull request merged**
