### PR TITLE
Added meta tag for mobile responsive in header.php file

### PR DESCRIPTION
**Pull request by vishal262**
Mobile responsive is not working properly so I have added meta tag

### CODE REVIEW

**Comment by jekkos** [comment]
@BudsieBuds any comments on this one?

**Comment by BudsieBuds** [comment]
@jekkos Same as the other ones. Unfortunately this doesn't magically make everything responsive. At least not in a ready for release kind of way.

@vishal262 Thanks for the contribution. You've probably seen that only the login page is responsive. Only the login page has been converted to Bootstrap 5, the rest of the app is still on Bootstrap 3 and will be upgraded once @objecttothis is finished with the big undertaking of converting the app from CodeIgniter 3 to version 4.

**Comment by jekkos** [comment]
Thanks for the input @BudsieBuds . I'm not very familiar responsive browser and such. Let's wait for a proper rework instead of merging something half baked. If other opinions please shoot @here

**Comment by objecttothis** [comment]
> Thanks for the input @BudsieBuds . I'm not very familiar responsive browser and such. Let's wait for a proper rework instead of merging something half baked. If other opinions please shoot @here

Making the webapp responsive just means that it scales well to devices of different screen sizes. Bootstrap takes care of all that and it's browser independent. I work with it in Foundation on another project all the time.  I created several issues regarding the remaining CI4 changes that need to be hammered out.  Once those are figured out then it's on to regression testing and debugging.  The more help I get, the faster it will go.

**Comment by jekkos** [comment]
Ok @objecttothis let's wait for a proper solution, thanks for all the hard work already.

**Pull request closed without merging**
