### PR TITLE
Merge errors patch

### PR DESCRIPTION
**Pull request by objecttothis**
It seems like I was careless in the rebase for the Sales controller and accepted some changes from the master that undid some of my changes to refactoring.  I need to download this build and test it before we merge to see if there are other issues.

Closing #3144

### CODE REVIEW

**Comment by jekkos** [comment]
the changeset is a bit confusing, it looks like there are quite some commits but only two files that were touched?

**Comment by objecttothis** [comment]
@jekkos this is likely because I submitted a single commit to the same branch that I merged from earlier and created a new pr. It shows the commit history of the branch but the changed files are only going to report what is different from the master.

**Comment by objecttothis** [comment]
the reason for it saying that it wants to merge 7 commits is that the original pr I did a squash and merge on, so in the master those appear as one commit, but in the branch they are still separate commits.

**Comment by jekkos** [comment]
Ok I see, maybe we should apply those changes on the squashed commit instead for clarity? If too hard I can try to do it for you.

**Pull request closed without merging**
