### PR TITLE
Add cost price column to item summary report

### PR DESCRIPTION
**Pull request by chunter2**

### CODE REVIEW

**Comment by chunter2** [comment]
@jekkos Not sure this is what you were talking about but it's an attempt.  :)  I was hoping I could edit both files and have them in one commit but didn't see how.

**Comment by jekkos** [comment]
@chunter2 exactly small changes like these are easy to check this way..

**Comment by jekkos** [comment]
@chunter2 I think builds are only ran if you create the branch in our repository directly. I have sent you an invite to become an organization member. Normally once accepted you should be able to do that.

**Comment by jekkos** [comment]
See my other PR, it will now build and deploy.

**Pull request closed without merging**
