### PR TITLE
Improves the behavior of dinner table selection.

### PR DESCRIPTION
**Pull request by SteveIreland**
This is an attempt to resolve the reported issue with dinner table selection.  I found one or two other issues with it that I also resolved.

### CODE REVIEW

**Comment by odiea** [comment]
It does not appear to be clearing the status flag in the dinner tables The status is unchanged after cancelling a Sale.
2019-07-20 13_47_27-Window

**Comment by odiea** [comment]
Both  2 and 3 were cancelled at the register after being Suspended. It appears the drop down is now showing the current un suspended Table.

**Comment by odiea** [comment]
Both tables 2 and 3 were cancelled. From the image you can see the Tables are not available for use.

2019-07-20 14_03_53-Window

**Comment by SteveIreland** [comment]
Okay. I will test it again.  Thanks for checking it out

**Comment by SteveIreland** [comment]
I'm happy you sent it back.  In addition to fixing the issue you found I realized that there were a couple of other items that needed to be addressed.

The Delivery and Takeaway should never be flagged as occupied, so I've corrected that.

And I also only update the dinner_tables table if the dinner table configuration is enabled.

**Comment by odiea** [comment]
Works great now.

**Comment by daN4cat** [comment]
Thanks @SteveIreland for the good work done. Shall we merge this?

**Comment by odiea** [comment]
I would say go ahead. It is a good improvement.

**Pull request merged**
