### PR TITLE
Blind sql injection fixes rework (#3284)

### PR DESCRIPTION
**Pull request by jekkos**
I have reinstated the fix from a month ago. Want to get this out to release the 3.3.6.

### CODE REVIEW

**Comment by odiea** [comment]
Applying this to Items the only column that sorts is the Item_id column. All other columns just sort the Item_id.

**Comment by jekkos** [comment]
Thanks for testing @odiea  I have checked your comment. Which column were you trying to sort? If I sort on name or category it does seem to work

**sorting on barcode**
Screenshot from 2021-09-28 09-22-07
Screenshot from 2021-09-28 09-22-01

**sorting on name**

Screenshot from 2021-09-28 09-21-50
Screenshot from 2021-09-28 09-21-56

**Comment by odiea** [comment]
Here is what I see. This was sorting on Name or Wholesale Price.
2021-09-28 02_03_04-Open Source Point of Sale _ Powered by OSPOS 3 3 5
2021-09-28 02_03_31-Open Source Point of Sale _ Powered by OSPOS 3 3 5
2021-09-28 02_04_00-Open Source Point of Sale _ Powered by OSPOS 3 3 5

**Comment by jekkos** [comment]
Ok weird, both cases seem to work fine on my end. I did force push a couple of times. Do you have the latest hash in use for the branch?

**Comment by odiea** [comment]
I downloaded this branch. © 2010 - 2021 · opensourcepos.org · 3.3.5 - 4b12b7.

**Comment by jekkos** [comment]
Ok thanks for the feedback, I have deployed the version to dev now and was checking, the name field does not sort correctly. I think the others do in fact.

**Comment by odiea** [comment]
Here is the code that I am testing out in Items.
$sort = $this->Item->sort_column($this->input->get('sort')); // controller
public function sort_column($field)
	{
		return array_key_exists($field, $this->db->list_fields('items')) ? $field : 'item_id';
	} // model

**Comment by jekkos** [comment]
Think it should be cfe927

**Comment by jekkos** [comment]
Indeed there is still issue, I'll try to debug it, thanks for the feedback

**Comment by odiea** [comment]
I tried changing this and it appears to sort the columns correctly now.
 return array_key_exists($field, $this->db->list_fields('items')) ? 'item_id' : $field;

**Comment by jekkos** [comment]
Did another push and seems better now on dev.

**Comment by odiea** [comment]
The only quirk I see now is on an older established db quantities does not sort? Looks ok on the Demo

**Comment by jekkos** [comment]
@odiea you mean the regular quantities field?

**Comment by jekkos** [comment]
@odiea should be fixed now.

**Comment by odiea** [comment]
Yes it is. Works good now.

**Comment by odiea** [comment]
What is the issue with placing the id before the $field?  I have had to do this to get some of the other tables to sort correctly.

**Comment by jekkos** [comment]
Well what the logic does it it checks if the supplied sorting column exists in the db, then applies it.

If some hacker tries to pass in some SQL for injection, it will be ignored as we only allow to sort on db column names. So that it was the statement does

**Comment by odiea** [comment]
But this does not appear to work correctly. I tried sorting in Customers, Suppliers and Employees and columns do not sort properly. The appear to sort to the id and not the column.

**Comment by jekkos** [comment]
Indeed well spotted, I think those three models need one more adapation

**Comment by odiea** [comment]
Try something on Gift cards and you may be done with this

**Comment by jekkos** [comment]
Ok the columns for giftcards are extended now. I've gotten two more security bug reports through this huntr.dev platform today. Not sure how this works but it seems that some researchers are looking for security bugs in ospos now.. which is good.

**Comment by jekkos** [comment]
The sale table might not work correctly yet.. The current approach will do some extra queries to fetch the database column names, which do not necessarily map to the column headers names.

I had a further look and there might be a better solution. The header names are already defined in the tabular_helper, but they are not in an accessible place. It might be better to extract those header arrays somewhere and then check for the field presence in each array separately.

**Comment by jekkos** [comment]
Links to #3965

**Comment by objecttothis** [comment]
@jekkos can we merge this into ci4-branch instead of master?  This fix will likely need to be applied to all sort and order fields in the various searches to close the vulnerability.  I realize it will likely mean porting the changes over to a new branch based on ci4-branch, but I'd hate to duplicate work.

**Pull request closed without merging**
