### PR TITLE
Restore code that was mistakenly "cleaned up"

### PR DESCRIPTION
**Pull request by SteveIreland**
This will restore the ability to update a sale.  Sorry ... I was overly enthusiastic about cleaning up code.

### CODE REVIEW

**Comment by skaman123** [comment]
have gud day Sir im a newbie here,  i've found an error on sales return on the part of a sale module
telling " Message: Use of undefined constant SALE_SALE - assumed 'SALE_SALE' ";

.....thanks

**Comment by odiea** [comment]
Have you updated the database. 3.1.1 to 3.2.0.sql

**Comment by skaman123** [comment]
Ok I do sir still error occured! as i've read the scripts unknown constant var SALE_SALE I think we can change this to var to SALE_TYPE_RETURN to fix this!...  ;)

..thanks

**Comment by SteveIreland** [comment]
Thanks @skaman123 .  I have a fix in play here.

**Comment by daN4cat** [comment]
Is the fix part of another PR?

**Comment by odiea** [comment]
How to duplicate this issue. I can not recreate it.

**Comment by SteveIreland** [comment]
Yes, I've included it in the changes for the item kit cost that I'm working on now.  Is that good enough or do you need a rush job on it?

**Comment by SteveIreland** [comment]
@odiea I actually haven't recreated it yet myself, but I confirmed that there is a code error.  It might not be noticeable unless you have the development flag set.  I was surprised it didn't appear during my earlier testing.

**Comment by daN4cat** [comment]
@SteveIreland fix the code error and submit the change, but @skaman123 would be good to understand in detail how to reproduce the error.

**Comment by odiea** [comment]
All I had to do was set it to development and then do a return.
2017-09-13 14_20_44-wedidit _ powered by ospos 3 2 0

**Comment by odiea** [comment]
$this->sale_lib->set_sale_type(SALE_TYPE_RETURN); appears to work without error for me.

**Pull request merged**
