### PR TITLE
Fix some typos + normalise some whitespace.

### PR DESCRIPTION
**Pull request by Maikuolan**
(PR affects only files located in `\application\language`).

### CODE REVIEW

**Comment by daN4cat** [comment]
Many files have been touched, what's the real change?
Also, could you please fix the translations from Weblate?

**Comment by WebShells** [comment]
Am not sure if spaces after php tags are a real problem in language files...

**Comment by Maikuolan** [comment]
> Also, could you please fix the translations from Weblate?

Didn't realise the translations here went through Weblate. No problem; I can do that. :-)

I'll also close this PR then, because there's no point accepting this PR if the translations will go through Weblate anyway.

> Am not sure if spaces after php tags are a real problem in language files...

No problem. The typos were the main purpose of this PR, and the whitespace changes were a secondary, last minute consideration. The typo fixes are a little buried under all the whitespace changes though. I didn't quite register just how big the number of files was until reading your comment and then looking back. '^.^

Anyway, if we're going through Weblate, it doesn't matter so much anyway. I'll close this now.

Thanks for the quick responses. :-)

**Comment by Maikuolan** [comment]
(I'm new to Weblate, so it may take me a little while to figure out how to find this repo's localisations on the Weblate platform. I'll send the typo fixes there once I figure it out though).

**Comment by WebShells** [comment]
No problem, please use http://translate.opensourcepos.org
Thanks for your contribution 👍

**Comment by daN4cat** [comment]
@Maikuolan By the way, thank you for the contribution! Looking forward to merge Weblate language amendments.

**Pull request closed without merging**
