### PR TITLE
Import update

### PR DESCRIPTION
**Pull request by objecttothis**

### CODE REVIEW

**Comment by objecttothis** [comment]
@jekkos I'm sure you've been thinking this, but I've decided that this PR is too unwieldy.  I've decided to break it into 4 PR's for everyone's sanity.  Here are the four PRs that I'm planning in order:
- Database indexing optimization scripts.
- Update items functionality via CSV file.
- Micro-optimizations throughout the code (replacing " in PHP with ' when not needed, because using it causes the parser to be invoked and refactoring queries to remove the "from" query builder call and placing the table in the get() which reduces method call frequency).
- Refactoring hungarian notation out of the code.

I can't merge any of it until 3.3.4 gets released.  What's your eta on 3.3.4?  In the meantime I'll setup the pull requests and test them, but I would rather not have to keep rebasing them (since I usually manage to screw up the rebase) so I'm hoping to create the branches and pull requests closer to when we are actually going to code review and merge.

**Comment by jekkos** [comment]
Hi @objecttothis we sort of got lost fixing bugs and then finding new bugs during this fixing. I've gave a last comment on the decimal/discount parsing issue and am planning to release after that is merged. I need some final confirmation on that issue so some last testing and verification would be nice

I think it's a good idea to split up the PR in functional parts as it will make the review and testing easier. Thanks for taking care of this.

**Comment by jekkos** [comment]
Release was done. Let's have a look at this one next?

**Comment by jekkos** [comment]
I'll wait a little bit more to see if anything urgent comes in and will then bump to 3.4.

**Comment by objecttothis** [comment]
> I'll wait a little bit more to see if anything urgent comes in and will then bump to 3.4.

Yeah, on Thursday I'll break out the first PR from this.  It should be pretty straight forward because it's just database optimizations.

**Comment by jekkos** [comment]
@objecttothis will you need to rebase this branch now with latest master?

**Comment by objecttothis** [comment]
> 
> 
> @objecttothis will you need to rebase this branch now with latest master?

Yes, but I'm slowly picking this PR apart and putting parts into other smaller PR's that are easier to rebase and test.

**Comment by objecttothis** [comment]
I think the next PR will be refactoring out the hungarian notation from the code.  It's pretty straightforward to do... its the rebasing that has to be precise.

**Pull request closed without merging**
