### PR TITLE
Add bosnian translations

### PR DESCRIPTION
**Pull request by jekkos**
This PR needs to have the system files added properly. Currently there is no official translation for bosnian. So I see two options here
* Add a translation project for CI in our weblate, to manage custom translations for CI within our project
* Try to contribute these translations to CI itself
* Create a new repo that holds custom system translations for CI (but not manage them through weblate)

### CODE REVIEW

**Comment by jekkos** [comment]
I have cloned CI translations repo to our organization and added bosnian language in there. Will make a PR back to have this hopefully merged in CI itself.

**Comment by cikov** [comment]
I'm sorry I just discovered these messages. i keep sticking to the initial ones

**Comment by cikov** [comment]
@jekkos Thank you very much. I don't know how the others but I couldn't handle all these actions

**Comment by cikov** [comment]
I gave my approval

**Pull request merged**
