### PR TITLE
Remove disables button when SALE COMPLETE button appears

### PR DESCRIPTION
**Pull request by dvbava**
I think it will make sense to not have disables control at 'sale complete' stage in sales register.

### CODE REVIEW

**Comment by mckaygerhard** [comment]
can you explain that @dvbava ?

**Comment by mckaygerhard** [comment]
i mean, some users are not so smart and need to see the "behaviour" of the buttons i think!

**Comment by dvbava** [comment]
The button itself changing to "Complete" from "Add payments", which is clear indication that it's good to proceed further.
For me personally, the monitor is 15" (1366x768 resolution), so saving space is equally important.
Once you are use to it, you will have no issue. however you have saved some space on register for long time.

**Comment by daN4cat** [comment]
The problem is that if somebody has a touch screen the UI shifts and the user will tend to push the wrong screen location.
That's why the disabled button is not removed to keep the layout and button position consistent.

**Comment by daN4cat** [comment]
In any case this will not merge in 3.2.0 as I want to release it this weekend.

**Comment by dvbava** [comment]
I see your point regarding touch scree. all right.

**Comment by mckaygerhard** [comment]
hi @dvbava if your space its the issue there's others options, try this: https://github.com/opensourcepos/opensourcepos/issues/1866#issuecomment-370199504 maybe gives you ideas, its a good hack

**Comment by dvbava** [comment]
@mckaygerhard, actually i have done some changes to https://github.com/dvbava/opensourcepos/tree/dev  and built it..works like magic!

**Comment by mckaygerhard** [comment]
please post/share some photos  here for more ideas! glad to see it helps to you @dvbava credits to @nerv55  that makes the hack, i'll try to document that in the wiki later days

**Pull request closed without merging**
