### PR TITLE
Manufacturer added to products

### PR DESCRIPTION
**Pull request by andriux1990**
I think it is very important to have a field for the manufacturer of the item... and to be able to use it in the future... in an easier way

### CODE REVIEW

**Review by daN4cat — COMMENTED** [review]
This commit is missing the database table change.
Also, I'm not sure why an attribute cannot do for the case.

**Review by daN4cat — CHANGES_REQUESTED** [review]
Please change.

**Comment by andriux1990** [comment]
> This commit is missing the database table change.
> Also, I'm not sure why an attribute cannot do for the case.

An attribute does it... but it's not the same... for example if we wanted to use the manufacturer's name as a search suggestion in sales... it's very easy... doing it with an attribute, it's very cumbersome

**Comment by WebShells** [comment]
By manufacturer you mean brand ? 
The supplier module already have Agency name and Supplier name, can't we make use of Agency name field as a brand rather than adding additional fields ? 
Thank you

**Comment by WebShells** [comment]
@andriux1990 That's why there is Agency name and Supplier name. So if you are buying Louis Vuitton from a different supplier the Brand is the Company name and the Agency Name is the Reseller ? Correct me if am wrong.

**Comment by daN4cat** [comment]
Maybe we should have brand as separate from company in Suppliers.

Louis Vitton as company owns different brands, agents are a sales entity.

**Pull request closed without merging**
