### PR TITLE
Responsive to mobile screens

### PR DESCRIPTION
**Pull request by andriux1990**
I always had this change ... it is something very simple. but I want this in the master version.

because in fact it adjusts very well to the screens of mobile devices

### CODE REVIEW

**Comment by jekkos** [comment]
Thanks for these changes @andriux1990 . 

Could you perhaps squash your commits to one so we have a clean history?
What is the actual gist of this changeset? I suppose the diff in header.php is crucial.

The classes you added on the submit buttons, are they really necessary to make it responsive? I suppose it changes the color of these buttons, no?

**Comment by BudsieBuds** [comment]
Hi @andriux1990!

I've got a few notes that I hope you agree with.

It's not good practice to not let a user zoom in, f.e. for accessibility reasons.

So this can be included in the header instead. The interface will be responsive.
`<meta name="viewport" content="width=device-width, initial-scale=1">`

Also, for your local build; there are a few typos in your code. See `maximun-scale` in the meta viewport and the header has the viewport line included twice.

FYI the login screen is being made responsive here #3190, the rest of the interface will hopefully follow soon.

**Comment by jekkos** [comment]
@andriux1990 this changeset will be superseeded by #3213

**Comment by andriux1990** [comment]
> @andriux1990 this changeset will be superseeded by #3213

@jekkos okay .. thank you very much

**Comment by jekkos** [comment]
Responsive fixes in master now

**Comment by mogsama** [comment]
I added some css to the end of public/public/dist/opensourcepos.min.css to make ospos better on mobile

responsive mobile
  
```
@media screen and (min-width: 240px) and (max-width: 991px) {
	.container {
		width: 100%;
	}

	.topbar {
		height: 0px;
		padding: 0;
	}
	
	.navbar .navbar-nav>li>a, .navbar-brand {
		float: right;
	}

	label {
		line-height: 36px;
	}
	
	#register_wrapper {
		width: 100%;
		margin-bottom: 50px;
		padding: 0 10px;
	}

	#overall_sale {
		width: 90%;
		margin-right: 5%;
	}

}

@media (min-width: 992px) {
  .container {
    width: 98%;
  }
}

@media (min-width: 1200px) {
  .container {
    width: 95%;
  }
}

@media (min-width: 1600px) {
  .container {
    width: 90%;
  }
}
```

**Comment by jekkos** [comment]
Looks nice @mogsama, someone really needs to make the register more responsive. Could you possibly make a pull request for this?

**Pull request closed without merging**
