### PR TITLE
added category column to the inventory summary report due huge produc… (#2526)

### PR DESCRIPTION
**Pull request by mckaygerhard**
we cannot provide search engine in huge products amounth but by addinding the categories we can also arange the report by categories... it's highly need!

closes https://github.com/opensourcepos/opensourcepos/issues/2526

### CODE REVIEW

**Comment by jekkos** [comment]
Looks fine to me, was anyone able to test / verify this PR?

**Comment by mckaygerhard** [comment]
no! i added one column due was very easy and also the changes are very minimal intrusive! addinding one filter or one kind of report aditional to the existing ones are very complicated, 

my proposition.. 

1. merege this.. due are pretty stable and easy also are need!
2. make a report engine spoecific for ospos (i'm working on it since some months)

**Comment by andriux1990** [comment]
> Looks fine to me, was anyone able to test / verify this PR?

I already tried it and it works very well, it is now easier to search for items by category.

please upload it to ospos

**Comment by mckaygerhard** [comment]
no! just merged! i added one column due was very easy and also the changes are very minimal intrusive!

addinding one filter or one kind of report aditional to the existing ones are very complicated,

my proposition if all of you want more fine-tune reports:

1. merge this.. due are lest intrusive in changes respect sources!
2. make a report engine spoecific for ospos (i'm working on it since some months)

**Comment by WebShells** [comment]
Looks fine then... Will merge...

**Pull request merged**
