### PR TITLE
Add decimals to items search result + fix reports

### PR DESCRIPTION
**Pull request by jekkos**
I simplified the attributes code a bit in items module. Also decimal attributes should show up in the results now.

### CODE REVIEW

**Comment by odiea** [comment]
Too bad bintray is not working to test this out!

**Comment by daN4cat** [comment]
Small I merge it to master and we test and fix if required?

**Comment by odiea** [comment]
I would wait and see if Jekkos also has a fix for the Date attribute search but I will leave it up to you 2.

**Comment by odiea** [comment]
Is this a true warning and not a possible issue?
Conflicting files
application/helpers/tabular_helper.php

**Comment by daN4cat** [comment]
Ok I'll wait.

**Comment by jekkos** [comment]
Does it make sense to search for dates in the attributes? I can add it but don't know if it's useful? (I won't use it)

**Comment by odiea** [comment]
I ended up copy and paste into the current master. I did not copy and paste the Report stuff.
I was able to add a new attribute ok and it now shows in the Items Table.
2019-06-20 15_06_32-Window
I did an Attribute search for it and the following was the result. This part appears to be ok so far.
2019-06-20 15_05_59-Window

**Comment by odiea** [comment]
I think it would be a nice addition for the folks that need to see their expiration dates.

**Comment by odiea** [comment]
I think the Date att would be kind of useless without it.

**Comment by WebShells** [comment]
Yes, it could be used as @odeia mentioned, for Expiry dates... By this maybe we can move on for creating additional report for items which will be expiring in a specific interval of time.

**Comment by andriux1990** [comment]
The pharmacies are obliged to keep a record of the medicines that are about to expire since the laboratories have return policies.

I think that being able to look for the products that are about to expire will help to be able to apply to the policy and thus be able to see which one has already expired in order to withdraw it.

**Comment by odiea** [comment]
I get the following error when I try to run the Detailed Transaction Report.
Error Number: 1064

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SEPARATOR '|') AS attribute_dvalues FROM `ospos_sales_items_temp` LEFT JOIN `osp' at line 1

SELECT `name`, `category`, `quantity_purchased`, `item_location`, `serialnumber`, `description`, `subtotal`, `tax`, `total`, `cost`, `profit`, `discount`, `discount_type`, `sale_status`, GROUP_CONCAT(DISTINCT CONCAT_WS('_', `definition_id`, attribute_value) ORDER BY definition_id SEPARATOR '|') AS attribute_values, GROUP_CONCAT(DISTINCT CONCAT_WS('_', `definition_id`, DATE_FORMAT(attribute_date, '%m/%d/%Y')) SEPARATOR '|') AS attribute_dtvalues, GROUP_CONCAT(DISTINCT CONCAT_WS('_', `definition_id`, attribute_decimal SEPARATOR '|') AS attribute_dvalues FROM `ospos_sales_items_temp` LEFT JOIN `ospos_attribute_links` ON `ospos_attribute_links`.`item_id` = `ospos_sales_items_temp`.`item_id` AND `ospos_attribute_links`.`sale_id` = `ospos_sales_items_temp`.`sale_id` AND `definition_id` IN (1,2,3,4,17,18) JOIN `ospos_attribute_values` ON `ospos_attribute_values`.`attribute_id` = `ospos_attribute_links`.`attribute_id` WHERE `ospos_sales_items_temp`.`sale_id` = '2612' GROUP BY `ospos_sales_items_temp`.`sale_id`, `ospos_sales_items_temp`.`item_id`

Filename: C:/wamp64/www/my-master/vendor/codeigniter/framework/system/database/DB_driver.php

Line Number: 691

**Comment by odiea** [comment]
The following line of code was missing a ")" but did I place it in the proper location.
				$this->db->select("GROUP_CONCAT(DISTINCT CONCAT_WS('_', definition_id, attribute_decimal) SEPARATOR '|') AS attribute_dvalues");

**Comment by daN4cat** [comment]
@odiea the code in master looks correct, was that a copy & paste mistake on your side?
Unless I look for that in the wrong place?

**Comment by odiea** [comment]
This is from the pull request. In models reports detailed receivings and detailed sales. I happened to find it using notepad ++.  I see 3 ( ( ( and only 2 ) ).			

				$this->db->select  (  "GROUP_CONCAT  (  DISTINCT CONCAT_WS  (  '_', definition_id, attribute_decimal SEPARATOR '|'  )   AS attribute_dvalues"  )  ;

**Comment by odiea** [comment]
I found out yesterday that Git Extensions will allow me to merge the pull requests. So hopefully no more copy and paste.

**Comment by daN4cat** [comment]
I'm sorry but I counterchecked and @jekkos code in that line looks correct to me.

> $this->db->select("GROUP_CONCAT(DISTINCT CONCAT_WS('_', definition_id, attribute_decimal) SEPARATOR '|') AS attribute_dvalues");

**Comment by daN4cat** [comment]
Yep, found it. I'm going to fix.

**Comment by odiea** [comment]
@daN4cat You might go ahead and merge this request so that others can test it. I am seeing no issues so far.

**Pull request merged**
