### PR TITLE
Upgrade phpunit to version 9.5

### PR DESCRIPTION
**Pull request by SteveIreland**
Testing to see if it builds.

### CODE REVIEW

**Comment by jekkos** [comment]
Currently seeing the following error
```

ospos_test | Fatal error: Declaration of CIPHPUnitTestCase::setUpBeforeClass() must be compatible with PHPUnit\Framework\TestCase::setUpBeforeClass(): void in /app/application/tests/_ci_phpunit_test/CIPHPUnitTestCase.php on line 75
```

It might be better to try and run the tests first locally and fix the issues encountered.

**Comment by jekkos** [comment]
From the error message it looks like the function signature for the test setup was changed.

**Comment by SteveIreland** [comment]
Okay, that will be a good learning opportunity for me.

**Comment by objecttothis** [comment]
@SteveIreland phpunit in ci4-upgrade is set to 9.6.3 so this PR can probably just be deleted.

**Comment by jekkos** [comment]
Will be obsolete after CI4 upgrade, will close this one for now.

**Pull request closed without merging**
