### PR TITLE
Fix default register mode (#3016)

### PR DESCRIPTION
**Pull request by jekkos**
This PR moves the config for default sale register mode to general, as it was under invoice before.

### CODE REVIEW

**Review by SteveIreland — COMMENTED** [review]
I downloaded and tested it.  It worked fine for me, except that I did notice a very minor issue that may not be worth the effort to fix.  The issue is that if I enable or disable the invoice feature, the register mode options under General are not refreshed to reflect the changes until after I exit config and return (or simply click on the Config icon to force a refresh).

**Comment by jekkos** [comment]
Code adapted as per the discussion. Will do a quick test to see if this works now.

**Comment by chunter2** [comment]
@jekkos I just tried applying this change and when I process a return the sales module comes back up set to return.  The same thing happens when I click cancel while processing a return.  I'm assuming this is supposed to go back to sale in both cases right?

**Comment by jekkos** [comment]
Yes I would expect it to reset (as the mode is cleared once the sale is completed)

**Comment by jekkos** [comment]
I did a quick test locally and it appears to work fine on my end. The register resets to sale after I complete a return or invoice.

**Comment by chunter2** [comment]
@jekkos I wonder if it has anything to do with me applying it on the 3.3.2 release.  Could there be a change between that release and now that's affecting things?  I tried applying the change without restarting apache and then with restarting.  Or could it be something with my browser cache?

**Comment by jekkos** [comment]
@chunter2 can you check if you have the line in the `clear_all` method to clear the mode? That one is crucial to make it work. I have checked again and can confirm it's fine on my side. Will merge and then let's try on dev server after.

**Comment by chunter2** [comment]
@jekkos I was missing the clear_all.  Sorry about that.  In my switching the code back and forth between your first commit and this one I missed re-adding that line.  It seems to be working as expected now.  Thanks again.

**Comment by jekkos** [comment]
Ok thanks for the testing and confirmation.

**Comment by lajeeshk** [comment]
As per the discussion what I understand, configuration for default register mode is moved to general tab. But I can't see that, can someone give me a screenshot?

**Comment by odiea** [comment]
That option was removed from the Configuration files.

**Pull request merged**
