### PR TITLE
CI4: Bugfix - add function to remove .env.bak issue #3826

### PR DESCRIPTION
**Pull request by owlbrudder**
Added function remove_backup() to security_helper.php. Added a call to this from the two places that call check_encryption where the backup is created. Added more defensive code to Config.php to ensure the encrypter  objectexists before it is called to avoid a crash.

### CODE REVIEW

**Comment by owlbrudder** [comment]
I renamed the branch. The old pull request is marked as closed and the branch history says I deleted it - presumably that is the rename action. The Travis build is still saying all checks have failed - is this automatically updated, or do we have to rerun a test manually?

**Comment by jekkos** [comment]
It is reran aitomatically once you push. You can Create a new branch from the current as folllows

git checkout -b remove-backup-env-file

Then push that to origin.

**Comment by jekkos** [comment]
Its probably the # as well thatis disallowed as a docker tag. So push a docker container is built using the branchname as tag.

**Comment by owlbrudder** [comment]
> Its probably the # as well thatis disallowed as a docker tag. So push a docker container is built using the branchname as tag.

Sigh. I have so much to learn. I will rename it again. Thank you.

**Comment by owlbrudder** [comment]
Branch renamed to CI4-Bugfix-to-remove-backup-env-file-after-migration and review requested. All checks passed this time so I have learned a valuable lesson: do not use hash symbols in names.

**Comment by jekkos** [comment]
Ok perfect, yeah sorry for the spelling errors I replied from my phone and the keyboard often autocorrects things in the wrong language. I tend to keep the branch names short and only use dashes between words. You can find some examples in this repository.

**Comment by owlbrudder** [comment]
> Ok perfect, yeah sorry for the spelling errors I replied from my phone and the keyboard often autocorrects things in the wrong language. I tend to keep the branch names short and only use dashes between words. You can find some examples in this repository.

I will try to keep my submissions less verbose. Honest.  :)

**Pull request closed without merging**
