### PR TITLE
Space removal

### PR DESCRIPTION
**Pull request by WebShells**
Additional spaces removal/alignment

### CODE REVIEW

**Comment by jekkos** [comment]
@WebShells thanks for this fix! While you are at it, I think that having the textarea might bring some issues with the PDF rendering. Would you mind to check and compare how the fields are rendered in regular templates? I think it was changed to a normal div not so long ago. Thanks

**Review by jekkos — CHANGES_REQUESTED** [review]
If you find the time maybe double check the textarea thingy.. thx

**Comment by WebShells** [comment]
> If you find the time maybe double check the textarea thingy.. thx
@jekkos wait let me apply it on all templates before we merge.

**Comment by WebShells** [comment]
@jekkos shall i replace also for number fields ? Can i have a screenshot how does it look so i can know what to fix?

**Comment by jekkos** [comment]
> @jekkos shall i replace also for number fields ? Can i have a screenshot how does it look so i can know what to fix?

Yes I'd replace all textarea items. It does not play well with dom2pdf.

**Comment by jekkos** [comment]
Thanks for the modifications done @WebShells .. 

I might have been wrong asking to change textarea for a div, in case of a column (td) we might not need to next an extra div.. I'll quickly verify if it's required and then wrap this one up.

**Comment by WebShells** [comment]
I can take care of that man no worries, ill check and confirm it

**Comment by jekkos** [comment]
Ok great thanks for going the extra mile here, I want to make sure we are not using any unneeded elements. Also I vaguely remember something in [html standard saying it is not something recommended ](https://stackoverflow.com/questions/1110915/is-a-div-inside-a-td-a-bad-idea).

**Comment by jekkos** [comment]
[Invoice-1.pdf](https://github.com/opensourcepos/opensourcepos/files/5625699/Invoice-1.pdf)

I have deployed this version on the dev server and did a quick test (check attached PDF). It seems the PDF generation is not working as it should (does not have any styles properly applied)

**Comment by jekkos** [comment]
This is a pdf generated from demo (3.2.2)

[2.pdf](https://github.com/opensourcepos/opensourcepos/files/5625748/2.pdf)

**Comment by jekkos** [comment]
Not sure but it could be that the invoice_email.css is not being imported. We need to check if this issue is also in master.. It might also be due to the dompdf upgrade

**Comment by jekkos** [comment]
EDIT: did a quick check and this 0.8.5 domPDF was already in 3.3.2, so it's probably not that

**Review by jekkos — CHANGES_REQUESTED** [review]
First we need to resolve the PDF generation issue

**Comment by jekkos** [comment]
@WebShells this might be same issue as #3019

**Comment by jekkos** [comment]
[Quote1.pdf](https://github.com/opensourcepos/opensourcepos/files/5694647/Quote1.pdf)
[Invoice1.pdf](https://github.com/opensourcepos/opensourcepos/files/5694652/Invoice1.pdf)
Invoice and quote PDFs look fine now. Proof attached here.

**Pull request merged**
