### PR TITLE
Fix Send Invoice PDF

### PR DESCRIPTION
**Pull request by SteveIreland**
This addresses the issue reported in #2301

### CODE REVIEW

**Comment by odiea** [comment]
I updated the current master with the changes that you made but the Screen version of the Invoice looks as follows. The lower table looks ok.
2019-04-21 11_53_37-Window

**Comment by SteveIreland** [comment]
That's not what I'm seeing in my tests so I will pull the branch down, and test it in other browsers.  I didn't make any change to the css used by the invoice.php view, just the email version.  So I don't know why you would be picking up css changes for the standard invoice view.

It also just now occurred to me that I don't have an email version for the tax invoice (although no one has fussed about that yet).

**Comment by odiea** [comment]
In invoice.php I changed the text area rows to 1 instead of 5 and it got the display I was looking four. Happy Easter

**Comment by SteveIreland** [comment]
Okay.  In the original pull request I replaced the text area in the invoice.php view with a DIV.  The text area control really doesn't play well with embedded `<BR/>` tags.

I downloaded the branch from bintray and tested it in both Chrome and Firefox and it behaved well in both browsers.  So I believe the original pull request is still good.

Edge doesn't work with my virtual hosts and since I hate Edge for any purpose other than displaying PDF files I'm not going to waste any more time trying to figure out how to configure it to work with it.  I saw a microsoft tech support thread on the topic that give me a very good reason not to waste any time with it.

The request was about the send invoice, but I now see that the send quote pdf and the send work order pdf have similar issues so I'm going to adapt those to behave the same and add them to this pull request.

If someone asks for a send tax invoice PDF I'll do that in a later change.

**Comment by odiea** [comment]
Ok The bintray download worked just fine. I sure won't submit issues from my master anymore.

**Comment by SteveIreland** [comment]
No problem @odiea   I've done the same.

The fixes for quotes and work orders won't be ready until next weekend.  Quotes and Work Orders are step-children to invoices and when I started adapting them I realized that they are lagging behind a bit on updates so I'd like to review and make some corrections there.  Plus when I touch them some of the existing code formatting may not make it past @daN4cat

**Comment by daN4cat** [comment]
I trust we are fine with this, confirmed @odiea ?

**Pull request merged**
